#! /bin/bash
cd /mnt/lfs/sources
wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.65.tar.bz2
wget http://ftp.gnu.org/gnu/automake/automake-1.11.1.tar.bz2
wget http://ftp.gnu.org/gnu/bash/bash-4.1.tar.gz
wget http://ftp.gnu.org/gnu/binutils/binutils-2.20.tar.bz2
wget http://ftp.gnu.org/gnu/bison/bison-2.4.1.tar.bz2
wget http://www.bzip.org/1.0.5/bzip2-1.0.5.tar.gz
wget http://ftp.gnu.org/gnu/coreutils/coreutils-8.4.tar.gz
wget http://ftp.gnu.org/gnu/dejagnu/dejagnu-1.4.4.tar.gz
wget http://ftp.gnu.org/gnu/diffutils/diffutils-2.8.1.tar.gz
wget http://prdownloads.sourceforge.net/e2fsprogs/e2fsprogs-1.41.10.tar.gz
wget http://expect.nist.gov/src/expect-5.43.0.tar.gz
wget ftp://ftp.astron.com/pub/file/file-5.04.tar.gz
wget http://ftp.gnu.org/gnu/findutils/findutils-4.4.2.tar.gz
wget http://prdownloads.sourceforge.net/flex/flex-2.5.35.tar.bz2
wget http://ftp.gnu.org/gnu/gawk/gawk-3.1.7.tar.bz2
wget http://ftp.gnu.org/gnu/gcc/gcc-4.4.3/gcc-4.4.3.tar.bz2
wget http://ftp.gnu.org/gnu/gdbm/gdbm-1.8.3.tar.gz
wget http://ftp.gnu.org/gnu/gettext/gettext-0.17.tar.gz
wget http://ftp.gnu.org/gnu/glibc/glibc-2.11.1.tar.bz2
wget http://ftp.gnu.org/gnu/gmp/gmp-5.0.0.tar.bz2
wget http://ftp.gnu.org/gnu/grep/grep-2.5.4.tar.bz2
wget http://ftp.gnu.org/gnu/groff/groff-1.20.1.tar.gz
wget ftp://alpha.gnu.org/gnu/grub/grub-1.97.2.tar.gz
wget http://ftp.gnu.org/gnu/gzip/gzip-1.4.tar.gz
wget http://sethwklein.net/iana-etc-2.30.tar.bz2
wget http://ftp.gnu.org/gnu/inetutils/inetutils-1.7.tar.gz
wget http://developer.osdl.org/dev/iproute2/download/iproute2-2.6.31.tar.bz2
wget http://ftp.altlinux.com/pub/people/legion/kbd/kbd-1.15.1.tar.gz
wget http://www.greenwoodsoftware.com/less/less-436.tar.gz
wget http://www.linuxfromscratch.org/lfs/downloads/6.6/lfs-bootscripts-20100124.tar.bz2
wget http://ftp.gnu.org/gnu/libtool/libtool-2.2.6b.tar.gz
wget http://www.kernel.org/pub/linux/kernel/v2.6/linux-2.6.32.8.tar.bz2
wget http://ftp.gnu.org/gnu/m4/m4-1.4.13.tar.bz2
wget http://ftp.gnu.org/gnu/make/make-3.81.tar.bz2
wget http://download.savannah.gnu.org/releases/man-db/man-db-2.5.6.tar.gz
wget http://www.kernel.org/pub/linux/docs/manpages/Archive/man-pages-3.23.tar.bz2
wget http://www.kernel.org/pub/linux/utils/kernel/module-init-tools/module-init-tools-3.11.1.tar.bz2
wget http://www.mpfr.org/mpfr-2.4.2/mpfr-2.4.2.tar.bz2
wget ftp://ftp.gnu.org/gnu/ncurses/ncurses-5.7.tar.gz
wget http://ftp.gnu.org/gnu/patch/patch-2.6.1.tar.bz2
wget http://cpan.org/src/5.0/perl-5.10.1.tar.bz2
wget http://pkgconfig.freedesktop.org/releases/pkg-config-0.23.tar.gz
wget http://procps.sourceforge.net/procps-3.2.8.tar.gz
wget http://prdownloads.sourceforge.net/psmisc/psmisc-22.10.tar.gz
wget http://ftp.gnu.org/gnu/readline/readline-6.1.tar.gz
wget http://ftp.gnu.org/gnu/sed/sed-4.2.1.tar.bz2
wget ftp://pkg-shadow.alioth.debian.org/pub/pkg-shadow/shadow-4.1.4.2.tar.bz2
wget http://www.infodrom.org/projects/sysklogd/download/sysklogd-1.5.tar.gz
wget ftp://ftp.cistron.nl/pub/people/miquels/sysvinit/sysvinit-2.86.tar.gz
wget http://ftp.gnu.org/gnu/tar/tar-1.22.tar.bz2
wget http://prdownloads.sourceforge.net/tcl/tcl8.5.8-src.tar.gz
wget http://ftp.gnu.org/gnu/texinfo/texinfo-4.13a.tar.gz
wget http://www.kernel.org/pub/linux/utils/kernel/hotplug/udev-151.tar.bz2
wget http://www.linuxfromscratch.org/lfs/downloads/6.6/udev-config-20100128.tar.bz2
wget http://www.kernel.org/pub/linux/utils/util-linux-ng/v2.17/util-linux-ng-2.17.tar.bz2
wget ftp://ftp.vim.org/pub/vim/unix/vim-7.2.tar.bz2
wget ftp://ftp.vim.org/pub/vim/extra/vim-7.2-lang.tar.gz
wget http://www.zlib.net/zlib-1.2.3.tar.bz2
wget https://www.nano-editor.org/dist/v4/nano-4.9.3.tar.gz
cd
